jobs:
- job: BaseBuild
  timeoutInMinutes: 0
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.13'
      windows_2017:
        imageName: 'vs2017-win2016'
      windows_2015:
        imageName: 'vs2017-win2016'
      alpine:
        imageName: 'ubuntu-16.04'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: choco install visualcpp-build-tools --version 14.0.25420.1 -fy
    condition: startsWith(variables['Agent.JobName'], 'windows_2015')
  - script: npm config set msvs_version 2015
    condition: startsWith(variables['Agent.JobName'], 'windows_2015')
  - script: npm install && npm run ci:build
    env:
      GITHUB_TOKEN: $(PersonalGithubToken)
